### ISSUE TITLE
Error: Loader.php in init_language() function

### ISSUE THREAD

**Issue by juangl** [feulf/rainframework#28]
I have a problem with  system/library/Loader.php on line 298:

``` php
$lang_id = $default_language ['lang_id'];
```

where $default_language variable is an integer.

sorry if I'm clumsy, it's my first day exploring rainframework, and I am a rookie with git

__EDIT__
The problem is that I have not installed language file. would be nice error message.

**Comment by feulf** [comment]
Hi Juan, thanks for reporting this, and yes it could be nice to throw an exception in this case.
