### ISSUE TITLE
Bug on installation

### ISSUE THREAD

**Issue by antonellomangone** [feulf/rainframework#4]
When I try to install Rain Framework following the documentation I got this error:

User Warning: CONTROLLER: FILE ../application/controllers/Content/Content.php NOT FOUND in /home/*******_/**_****_/**_****/rainframework/Rain/library/Controller.php on line 38
-/home/antonello/php_web/webapps/rainframework/Rain/library/Loader.php : 85
-/home/antonello/php_web/webapps/rainframework/application/bootstrap.php : 22
-index.php : 24

the problem is that the directory ../application/controllers/Content/Content.php (Content) is lower case ../application/controllers/content/Content.php

and If I correct the problem ... the application doesn't load the default template ...

**Comment by feulf** [comment]
Hey, is a case sensitive issue that we've to fix, I'll keep you update on
that
thanks for reporting

**Comment by feulf** [comment]
Thanks for your report, we renamed correctly the folders name and now seems to work good. Let us know if this issue still happen.

**Comment by antonellomangone** [comment]
When you download and unzip the folder of rainframeworks under localhost it works, but it doesn't render the default template and the signle links doesn't works ...

http://localhost/github/rainframework/index.php/Form/

Not Found

The requested URL /github/rainframework/index.php/Form/ was not found on this server.
Apache/2.2.17 (Ubuntu) Server at localhost Port 80

I suggest you to test it under linux

**Comment by feulf** [comment]
It will be done, thanks again
