### ISSUE TITLE
installation bug

### ISSUE THREAD

**Issue by antonellomangone** [feulf/rainframework#7]
When you download and unzip the folder of rainframeworks under localhost it works, but it doesn't render the default template and the signle links doesn't works ...

http://localhost/github/rainframework/index.php/Form/

Not Found

The requested URL /github/rainframework/index.php/Form/ was not found on this server.
Apache/2.2.17 (Ubuntu) Server at localhost Port 80

I suggest you to test it under linux

**Comment by feulf** [comment]
We changed the structure of the framework and also removed uppercase from controller and model, to avoid any case error. The installation now should work fine.
